# Generated by Django 6.0 on 2026-01-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('desccription', models.TextField()),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
